export const ariaToHtmlMapping = {
  button: ["button", "summary", "input[type=submit]", "input[type=reset]"],
  caption: ["caption"],
  cell: ["td"],
  blockquote: ["blockquote"],
  code: ["code"],
  checkbox: ["input[type=checkbox]"],
  combobox: ["select"],
  dialog: ["dialog"],
  group: ["fieldset", "details", "optgroup"],
  figure: ["figure"],
  form: ["form"],
  heading: ["h1", "h2", "h3", "h4", "h5", "h6"],
  img: ["img"],
  link: ["a[href]"],
  list: ["ul", "ol", "menu"],
  listbox: ["select[multiple]"],
  listitem: ["li"],
  term: ["dfn", "dt"],
  definition: ["dd"],
  option: ["option"],
  generic: ["div"],
  paragraph: ["p"],
  meter: ["meter"],
  progressbar: ["progress"],
  slider: ["input[type=range]"],
  radio: ["input[type=radio]"],
  region: ["section"],
  row: ["tr"],
  rowgroup: ["thead", "tbody", "tfoot"],
  rowheader: ["th[scope=row]"],
  columnheader: ["th[scope=col]"],
  search: ["search"],
  searchbox: ["input[type=search]"],
  strong: ["strong"],
  status: ["output"],
  emphasis: ["em"],
  separator: ["hr"],
  deletion: ["del"],
  insertion: ["ins"],
  spinbutton: ["input[type=number]"],
  textbox: ["input[type=text]", "textarea"],
  table: ["table"],
  article: ["article"],
  banner: ["header"],
  complementary: ["aside"],
  contentinfo: ["footer"],
  main: ["main"],
  math: ["math"],
  navigation: ["nav"],
  subscript: ["sub"],
  superscript: ["sup"],
  time: ["time"],
  webarea: ["body"],
  none: [
    "head",
    "html",
    "title",
    "base",
    "link",
    "meta",
    "style",
    "script",
    "noscript",
    "template",
    "slot",
    "iframe",
    "noembed",
  ],
  presentation: [""],
  media: ["area", "audio", "canvas", "embed", "object", "video"],
};
