export const ariaToHtmlMapping = {
  button: [
    "button[type=button]",
    "button",
    "summary",
    "input[type=submit]",
    "input[type=reset]",
  ],
  caption: ["caption"],
  cell: ["td"],
  blockquote: ["blockquote"],
  code: ["code"],
  checkbox: ["input[type=checkbox]"],
  combobox: ["select"],
  dialog: ["dialog"],
  group: ["div[role=group]", "fieldset", "details", "optgroup"],
  figure: ["figure"],
  form: ["form"],
  heading: ["h1", "h2", "h3", "h4", "h5", "h6"],
  img: ["img"],
  link: ["a[href]"],
  list: ["ul", "ol", "menu"],
  listbox: ["select[multiple]"],
  listitem: ["li"],
  term: ["dfn", "dt"],
  definition: ["dd"],
  option: ["option"],
  generic: ["div"],
  paragraph: ["p"],
  meter: ["meter"],
  progressbar: ["progress"],
  slider: ["input[type=range]"],
  radio: ["input[type=radio]"],
  region: ["section"],
  row: ["tr"],
  rowgroup: ["tbody", "thead", "tfoot"],
  rowheader: ["th[scope=row]"],
  columnheader: ["th[scope=col]"],
  search: ["search"],
  searchbox: ["input[type=search]"],
  strong: ["strong"],
  status: ["output"],
  emphasis: ["em"],
  separator: ["hr"],
  deletion: ["del"],
  insertion: ["ins"],
  spinbutton: ["input[type=number]"],
  textbox: ["input[type=text]", "input:not([type])", "textarea"],
  table: ["table"],
  grid: ["table[role=grid]"],
  tree: ["ul[role=tree]", "ol[role=tree]"],
  treeitem: ["li[role=treeitem]"],
  tab: ["button[role=tab]"],
  tabpanel: ["div[role=tabpanel]"],
  tablist: ["ul[role=tablist]"],
  treegrid: ["table[role=treegrid]"],
  toolbar: ["div[role=toolbar]"],
  tooltip: ["div[role=tooltip]"],
  menu: ["ul[role=menu]", "ol[role=menu]"],
  menubar: ["div[role=menubar]"],
  menuitem: ["li[role=menuitem]"],
  menuitemcheckbox: ["li[role=menuitemcheckbox]"],
  menuitemradio: ["li[role=menuitemradio]"],
  article: ["article"],
  banner: ["header"],
  complementary: ["aside"],
  contentinfo: ["footer"],
  main: ["main"],
  math: ["math"],
  navigation: ["nav"],
  subscript: ["sub"],
  superscript: ["sup"],
  time: ["time"],
  webarea: ["body"],
  none: [
    "head",
    "html",
    "title",
    "base",
    "link",
    "meta",
    "style",
    "script",
    "noscript",
    "template",
    "slot",
    "iframe",
    "noembed",
  ],
  presentation: [""],
  media: ["embed", "area", "audio", "canvas", "object", "video"],
};
